name = "STLDecomposition"
uuid = "3463f4e6-5c23-45f0-ad9a-7850d654c7dd"
authors = ["William Beng"]
version = "1.0.0-DEV"

[deps]
stldecomposition_jll = "d8cc2a31-0abf-5619-8b1f-2aa308935162"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
